# general configuration
url: https://messengeranonymous.com
baseurl: ''

# compass configuration
compass:
  name: "Messenger Anonymous"
  # an avatar or logo (optional)
  logo: "/images/spy.png"
  # author will appear under the avatar (optional)
  author: "Dave Kelly"
  # tagline will appear under the title (optional)
  tagline: "Send 20 anonymous messages with a random friend on Facebook!"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty